### ISSUE TITLE
Can you change/update an overlay's opacity from angular?

### ISSUE THREAD

**Issue by nickponline** [tombatossals/angular-leaflet-directive#251]
I tried adding a button to my controller

$scope.onClick = function() {
 $scope.layers.overlays.myOverlay.layerOptions.opacity = 0.5;
}

Although the value changes, the new opacity does not reflect on the map.

**Comment by nmccready** [comment]
@ccrabb please PR.

**Comment by elesdoar** [comment]
Hi, layercontrol do it, an example here:

http://tombatossals.github.io/angular-leaflet-directive/examples/0000-viewer.html#/controls/custom-layer-control-example

This feature requires HTML5 browsers.

**Comment by nmccready** [comment]
Actually @elesdoar I think they know how to set the opacity. I think the issue is that updating the opacity doesn't work at a later point in time.

**Comment by nmccready** [comment]
Does anyone want credit for their work? Please make a PR; or do I have to pull it in manually. Please make our lives easier by making a PR through github.

**Comment by elesdoar** [comment]
I think that it was clear, layercontrol support change opacity and order in layers.

Click double down arrow

![github1](https://cloud.githubusercontent.com/assets/3817595/9610150/5dfa9902-509d-11e5-957b-730fef9915e2.png)

Layer control show an opacity control

![github2](https://cloud.githubusercontent.com/assets/3817595/9610151/5dfd4508-509d-11e5-95aa-70ae6a8d2f2c.png)

The problem is that leaflet directive not watch opacity or z-index changes without layercontrol.

**Comment by nmccready** [comment]
Ok @elesdoar then we should be good "as is" and close right?

**Comment by elesdoar** [comment]
For now, yes, soon I will fixing for be enough setting layer options anywhere...
