### ISSUE TITLE
Center keeps updating

### ISSUE THREAD

**Issue by hvisser** [tombatossals/angular-leaflet-directive#254]
I have a map with a custom projection (crs) for which I set the center. What I observe is that  the `onmoveend` is fired from leaflet again, in response to updating the map center model. I noticed that cc1388fdfb0c4c96f7e14456d673b02a4244df28 looks like an attempt to fix this, but that does not work for me. In the center directive the `changingModel` is set to false, but the `onmoveend` event fires after setting that var, causing the center to be updated again. I'm not sure how to fix this properly, but I can of course assist in helping you fix this ;)

**Comment by nmccready** [comment]
So in my baseMap factory which I utilize in my controller I always throttle the mosemove and maybe the mouseend end events. See here http://stackoverflow.com/questions/16645766/google-maps-api-v3-no-smooth-dragging

**Comment by nmccready** [comment]
I also do my darnedest to implement something similar to google maps idle event since leaflet has none.

See here and my comment about issues with moveend and load http://stackoverflow.com/questions/23622644/leaflet-map-event-equivalent-to-google-map-idle-event 

https://github.com/Leaflet/Leaflet/issues/3178

**Comment by nmccready** [comment]
Is this still a problem?

**Comment by nmccready** [comment]
closing until I get feedback.
