### ISSUE TITLE
Unable to use controllerAs syntax on controls attribute

### ISSUE THREAD

**Issue by Raptormstr** [tombatossals/angular-leaflet-directive#348]
jQuery considers the attribute "controls" as a reserved word and will rename any string to simple "controls".  Look at the jQuery.js source code lines 623 & 6888 for 2.1.0 and 665 & 7960 for 1.11.0.  I do not believe jqLite has this same issue.

For example:
Before $compile: \<leaflet controls="ctrl.myCustomControls"></leaflet>
After $compile: \<div class="angular-leaflet-map ng-scope" controls="controls"></div>

NOTE: I removed the other attributes and classes for brevity.

The only workaround if jQuery is required is to use the variable name "controls" and assign it to the $scope.

**Comment by jsthivierge** [comment]
Got a similar problem. I used grunt-contrib-htmlmin task to minimize my html and since controls is a HTML5 attribute and my scope variable is named controls (&lt;leaflet controls="controls"&gt;&lt;/leaflet&gt;), it got renamed to &lt;leaflet controls&gt;&lt;/leaflet&gt;. 

The htmlmin task option <a href="http://perfectionkills.com/experimenting-with-html-minifier/#collapse_boolean_attributes">collapseBooleanAttributes</a> was set to true, therefore controls="controls" was collapsed to controls since it's an html5 attribute...

Any idea if the attributes will be renamed soon to prevent this type of conflict?

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#18

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
