### ISSUE TITLE
Using 'center' as a directive name conflicts with other code

### ISSUE THREAD

**Issue by wylieconlon** [tombatossals/angular-leaflet-directive#535]
If I include the `center` attribute anywhere that this directive has been loaded, it causes this error:

    Error: [$compile:ctreq] Controller 'leaflet', required by directive 'center', can't be found!

This occurs because I have another plugin that uses a `center` attribute as configuration. Would you consider namespacing this attribute as leaflet-center or something else non-conflicting?

Here is a demo link: http://jsbin.com/qurava/1/edit?html,js,console,output

**Comment by mbajur** [comment]
Any progress or *official* dirtyhack on this? :)

**Comment by elmagicogt** [comment]
hey Tombatossals. Any update on this issue? Would be nice to have it corrected. :)

thanks

**Comment by nolandubeau** [comment]
Any update on this?
Thanks.

**Comment by sprattek** [comment]
+1 <code>lf-</code>

**Comment by wylieconlon** [comment]
There is no workaround that I'm aware of for this.

**Comment by aga-glabala** [comment]
@tombatossals 
Hi, this bug is blocking us in our current project (we need leaflet and google maps directives and they both use center). Are you working on this? 

I thought I could fix that and I came up with few ideas how to make that:
1) As proposed before, we could add prefix to those directives (center, bounds, marker, paths). The drawback is we loose backward compability. 
2) We could try not to force leaflet directives for marker directive (set warning and some return to prevent logic to perform. I am not sure if this will work, but that's the easiest way to do it.
3) We could move all logic from those directives to services, replace directives by main directive parameters. The leaflet directive syntax would be untouched, so we would still have backward compatibility. That's to hardest way to do it, but I think it is also the most elegant solution.

What do you think? Did you plan some major changes too so we could drop backward compatibility? (maybe in version 1.0? ;) ) Should I try resolve this by myself or you have been working on that? 
My gmail and hangout login is aga.glabala if you are interested in longer discussion about this issue.

Agnieszka Świecznik

**Comment by thibaudkistler** [comment]
Any update on this? adding lf- sounds like a great idea! :)

**Comment by nmccready** [comment]
Hey all we'll get to this; nagging won't help. remember this is free. Feel free to dig in and try to give back and fix it.

**Comment by nmccready** [comment]
Moved to 0.9.0 milestone since this is a breaking change.

**Comment by simison** [comment]
Consider adding `lf-center` already now and remove `center` later in 0.9?

**Comment by nmccready** [comment]
Hmm.. ok we should really do all of them with `lf-` and leave the originals. But it honestly complicate the code now when just cutting to 0.9.0 will just be directive renames. Not sure about this; but I guess we could just do this for center.

**Comment by nmccready** [comment]
#914 PR
