### ISSUE TITLE
leafletDirectiveMarker.click is not related to the controller scope ?

### ISSUE THREAD

**Issue by Getz85** [tombatossals/angular-leaflet-directive#597]
I have multiple map on the same page, each one in a different controller.

Only one of the map must react to marker click. 

I define the listener into the first controller:

```javascript
$scope.$on('leafletDirectiveMarker.click', function (e, args) {
    alert('Marker in map 1 clicked');
});
```

The problem is that if I click on a marker on the other map, the alert is shown: http://jsfiddle.net/dy17mbm5/3/

I tried to override the event in the second controller, but both are called when I click on a marker: 
http://jsfiddle.net/c3jexokn/

Is it a bug or am I doing something wrong?

**Comment by tombatossals** [comment]
Seems like a bug, I'm going to take a look at this, thanks for reporting.

**Comment by tombatossals** [comment]
Hi @Getz85 , I have changed the marker events logic, by default now we "emit" to the related parent scopes, instead of broadcasting. It seems better this way as you report.

Take a look at this example, based on yours. Now I think its working fine:
http://tombatossals.github.io/angular-leaflet-directive/examples/markers-two-maps-events-example.html

In any case, the "event" related funcionality of this directive needs some work .

Thanks so much for reporting and for the example!
