### ISSUE TITLE
Optimizing geojson directive to use addData method 

### ISSUE THREAD

**Issue by facultymatt** [tombatossals/angular-leaflet-directive#609]
Currently the geojson directive works by removing the geojson layer and creating it from scratch on every change. 

This is not performant, and is not needed in many cases, for example: 

- When a new element is added to an array of geoJson data
- When an existing element is removed (although limitations exist since there is no removeData method, see https://github.com/Leaflet/Leaflet/issues/1416)

For the first point, we could use the [addData](http://leafletjs.com/reference.html#geojson-adddata) API to eliminate the need for removing the entire layer. 

---

Additionally, what is the most performant way to use the directive as it currently exists? Any tips on this?

**Comment by newmanw** [comment]
+1

Great directives, but lacking dynamic support for vector layers

**Comment by amyhua** [comment]
+1

**Comment by nmccready** [comment]
@facultymatt this could be fairly simple in a few ways. Currently I use this directive with watches disabled  and explicitly up send in the updated model via create and clean on a directiveControl. The addition of a add / newData method would be trivial. However, it would be better to be consistent so all directiveControls are similar.

We could also add some logic to figure out what the newData is within watches but that too will need to configurable. This is because the more logic comparing in the watch the slower the watch becomes. Therefore should the newData be figured out by the application and if so why use the watch (use directiveControl).  I am just thinking out loud here before any code is written.

**Comment by nmccready** [comment]
This issue was moved to angular-ui/ui-leaflet#43

**Comment by tombatossals** [comment]
I'm going to rework&redesign angular-leaflet-directive to be compatible with Leaflet v1.0. It will mantain almost all its functionality, and will be compatible with the current features of the directive, but I must start from a fresh point, so I'm going to close this issue. If you think it must be worked with the new version, please reopen it.
