### ISSUE TITLE
leafletFirectiveMap.click is not firing

### ISSUE THREAD

**Issue by stigmat4j** [tombatossals/angular-leaflet-directive#641]
Hello. Sorry for my English :)

Event leafletDirectiveMap.click is not firing on my Android device.
My code
```js
for  (var k in mapEvents) {
    eventName = 'leafletDirectiveMap.' + mapEvents[k];
    $scope.$on(eventName, function() {
        $scope.eventDetected = event.name;
    });
}
```
Just firing other events excepting "leafletDirectiveMap.click".
If you need another code blocks, i will send to the issue.

**Comment by seadour** [comment]
Hi @stigmat4j, I am having this same issue right now. Were you able to find a solution in your case?

**Comment by seadour** [comment]
Ah actually, I just figured it out. I needed to explicitly declare the events in my `$scope`, as such:

    angular.extend($scope, {
      events: {
        map: {
          enable: ['click'],
          logic: 'emit'
        }
      },
      ...
    });

Then I can capture the event like this:

    $scope.$on('leafletDirectiveMap.click', function (event, args) {
      //do something
    });

This wasn't intuitive because other event listeners like `leafletDirectiveMarker` and `leafletDirectivePath` work fine without adding them to the `events` sub-object.
