### ISSUE TITLE
v0.8.6 Broke custom controls

### ISSUE THREAD

**Issue by adgoncal** [tombatossals/angular-leaflet-directive#874]
Hi, 

I just noticed that 0.8.6 breaks custom controls.

In 'src/services/leafletControlHelpers.js', function isValidControlType is checking if the control is in controlTypes object, but 'custom' is not. 

In 'src/directives/controls.js', it calls isValidControlType to check if the control is valid, but returns early on custom controls.

**Comment by MarkAPhillips** [comment]
I have this problem also and had to revert back to 0.8.5

**Comment by nmccready** [comment]
@elesdoar @tombatossals ?

@adgoncal @MarkAPhillips please checkout this PR as it changed. https://github.com/tombatossals/angular-leaflet-directive/pull/831

My guess is we should have moved to 0.9.X

**Comment by sibbl** [comment]
There are more troubles than just `"custom"` not returning `true` when calling `isValidControlType`. One could use an array of controls for `custom` in 0.8.5, this doesn't work anymore as well. I guess this needs some more rewriting.

**Comment by MarkAPhillips** [comment]
If there are issues in this, can it be reverted and then pushed when fully tested and documented into 0.9.0 rather than 0.8.6. I need to review the changes as in the current state it completely breaks my application. @tombatossals  can you advise how this is to be addressed so I can decided how I should proceed. I do not mind reworking my control code but before I start if you intend to fix the issues in the next week will hold off until then - thanks.

**Comment by paambaati** [comment]
Stuck on the same boat; I'm working on a new app and I suppose the exact wrong time to write a custom control - none of the examples work, and the documentation doesn't apply anymore. For now, I'm just hacking into the main distributable as a stop-gap, but it would be great if documentation at least shows 1 example with adding a new custom control.

**Comment by Diones** [comment]
Exactly, the same here. Version 0.8.5 working fine.

**Comment by nmccready** [comment]
@tombatossals should we go to 0.9.X and is controls working in a different manner now? #899

**Comment by nmccready** [comment]
Also is there new documentation for this?

**Comment by tombatossals** [comment]
Hi, sorry I haven't used custom controls before, and there was no test nor example showing how they must work. I have solved the issue in the last commit, and added a new example of how to load a custom example.

@nmccready the controls works the same way as before, they were reworked to be able to extend and add new controls to the library easily, but maybe is a good moment to go to 0.9.x.

No new documentation needed, because they work as before (now at least).

**Comment by nmccready** [comment]
Cool ty

**Comment by nmccready** [comment]
Cutting a new release soon closing.
